### ISSUE TITLE
Incompatibility with modernifix (probably caused by multithreading)

### ISSUE THREAD

**Issue by MrGrape** [mactso/HarderSpawners#8] opened 2023-12-03 21:04 UTC
Here is ny crash report, mod versions can be found here:
[crash-2023-11-28_00.43.01-server.txt](https://github.com/mactso/HarderSpawners/files/13540215/crash-2023-11-28_00.43.01-server.txt)
Not a java dev myself but I think that this can be solved by placing a mutex somewhere

**Comment by IIIpl4sm4III** [comment] 2024-06-04 04:36
@mactso Can we get an update on this? Affecting multiple modpacks, my instance is from HarderSpawners-1.19.1-43.2.24.0. Should also note Modernfix is installed alongside this mod. https://pastebin.com/JLPTHpzN

**Comment by mactso** [comment] 2024-06-13 03:44
Hi, starting to look at this now.   Sorry for the delay but went 7 days without electricity from a Derecho storm.
Just getting back on my feet this week.

I'll update you in the next 24 hours.

**Comment by mactso** [comment] 2024-06-13 04:01
The code in question is synchronized.

ServerTickHandler.java
...
       private static List<WeakReference<SpawnerBlockEntity>> sbelist = new ArrayList<>();
	@SubscribeEvent
	public void onServerTickEvent(ServerTickEvent event) {

		if (event.phase == Phase.END && (--ticks) <= 0) {
			ticks = 20;
			synchronized (sbelist) {
				Iterator<WeakReference<SpawnerBlockEntity>> it = sbelist.iterator();
				while (it.hasNext()) {
					SpawnerBlockEntity sbe = it.next().get();
					if (sbe == null || sbeTest(sbe))
						it.remove();
				}
			}
...
		}

and below...

	public static void addSbeWorklistEntry(SpawnerBlockEntity sbe) {
		if (Thread.currentThread().getName().equals("Render thread"))
			return;
		synchronized (sbelist) {
			sbelist.add(new WeakReference<>(sbe));
		}
	}

Are the only references.    I can't see the issue in my code.  Do you have any ideas?

**Comment by mactso** [comment] 2024-06-13 04:10
The java code that is failing is
"        final void checkForComodification() {
            if (modCount != expectedModCount)
                throw new ConcurrentModificationException();
        }
"

I can't see how this would happen unless the synchronization is being removed or disabled somehow.
The counter would be increased when it entered the synchronized code and decrement when it left the code.
I'll see if I can find anything on this elsewhere.

Not going to point the finger at modernfix just yet.  They seem pretty sharp.

**Comment by mactso** [comment] 2024-06-13 04:15
Is this running on a dedicated server?

**Comment by IIIpl4sm4III** [comment] 2024-06-13 04:25
> Is this running on a dedicated server?

It is

**Comment by mactso** [comment] 2024-06-13 06:33
This was with the 1.19.2 version of Modernfix and the 1.19.X version of Harder Spawners.

The error you reported appears to be happening inside Arraylist java "synchronized" which may indicating multiple instances of Harder Spawners may be running in memory.

So I've run this for 2 hours with only harder spawner and modern fix ( it recommended Ferrite but started anyway )  with many spawners flew around to various spawners and had no crashes.  You may want to have ModernFix take a look at the code as I can't see any obvious issues with the harder spawners code.  It's very straightforward.

**Comment by mactso** [comment] 2024-06-13 06:33
Going to get some sleep for now.

**Comment by mactso** [comment] 2024-06-26 21:11
Sorry I was unable to resolve this better.   But I couldn't make it break and it was synchronized.   All I could guess was the other mod was somehow running multiple copies of the mod in memory at the same time and disabling the synchronization code for performance reasons.

Going to close this issue.

**Closed as completed by mactso** 2024-06-26 21:11 UTC

**Comment by iiiodel** [comment] 2024-07-26 18:35
Hello. Sorry for commenting on a closed issue. In the modpack I'm currently using, I'm getting a crash caused by the HarderSpawners mod while pregenning the world with chunky. There are other people who are getting the same error I'm getting while pregenning. There is even a person who encountered this problem while playing normally and crashed the game. But I cannot verify this issue because I have not encountered it myself. I am ready to provide the necessary logs and data. If you want, I can also share the modpack I use and the discord server of that pack. Is it possible to find a solution to this issue? I think you will encounter the same problem when you make a dedicated server with the same mod pack and pregen it.
